force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <description>Stores patient information. Tracks whether a patient is self-funding or insured and links to an insurance company if applicable.</description>
    <label>Patient</label>
    <nameField>
        <label>Full Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Patient__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Patient&apos;s profile on Patient Portal.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ShareEvent__e/ShareEvent__e.object-meta.xml
<CustomObject>
    <label>Share Event</label>
    <pluralLabel>Share Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/ShareEvent__e/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>ObjectName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/handlers/PatientTriggerHandler.cls
public without sharing class PatientTriggerHandler {
    
     //Determines when Patient__c records need to be shared with the assigned portal user.
    public static void queueShareEvents(List<Patient__c> newList, Map<Id, Patient__c> oldMap) {
        if (UserInfo.getUserType() == 'PowerCustomerSuccess') return;

        List<ShareEvent__e> events = new List<ShareEvent__e>();

        for (Patient__c p : newList) {
            if (p.User__c == null) continue;

            if (Trigger.isInsert ||
                (Trigger.isUpdate && 
                 (p.User__c != oldMap.get(p.Id).User__c || 
                  p.OwnerId != oldMap.get(p.Id).OwnerId))) {

                events.add(new ShareEvent__e(
                    RecordId__c = p.Id,
                    ObjectName__c = 'Patient__c'
                ));
            }
        }

        if (!events.isEmpty()) EventBus.publish(events);
    }
}